### ISSUE TITLE
unable to link css file in denjucks template file

### ISSUE THREAD

**Issue by ashokbuxar** [denjucks/denjucks#5]
I am using deno and denjucks as templating engine. in template .html file header section, I am linking my external css file but failed. the code-

`  
<link` rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" href='../static/style.css'>
`
the file format is -

main
 static
  style.css
 templates
  index.html
Bootstrap link is working but custom css link is not working. Please suggest what is wrong.

**Comment by denjucks** [comment]
Is it giving you an error message? This shouldn't be an issue with denjucks, as no template is being used in the above here from my understanding.

**Comment by ashokbuxar** [comment]
agreed. this is not due to denjucks. it is happening somewhere in oak. How to solve that, I am not getting any idea.

**Comment by denjucks** [comment]
Here is a link to serving static content with Oak: [link](https://github.com/oakserver/oak#static-content). Hope this helps! Gonna close this issue
